/**
 * 全局的业务属性常量在这里定义，页面通过 $const 引用
 */

const fs = require('fs-extra')

const DOWNLOAD_URL = ''

// 根据检查项匹配检查项说明
const getChecksForIds = (ids) => {
	return ids.map(id => {
		return ksChecks.find(item => item.id === id)
	})
}

// 业务检查项
const ksChecks = [{
		"indexs": [
			"身高",
			"体重",
			"体重指数",
			"收缩压",
			"舒张压"
		],
		"id": 330,
		"code": "1.2.1.1",
		"py": "YBJCA",
		"name": "一般检查A",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 8,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过仪器测量人体身高、体重及血压，科学判断体重是否标准、血压是否正常。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2024-03-18 13:59:34",
		"ipaddress": "10.33.21.87",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "一般检查室",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"病史",
			"家族史",
			"心率",
			"心律",
			"心音",
			"肺部听诊",
			"肝脏触诊",
			"脾脏触诊",
			"肾脏叩诊",
			"内科其它"
		],
		"id": 1,
		"code": "1.4.1.1",
		"py": "NK",
		"name": "内科",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 16,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过视、触、叩、听检查心、肺、肝、脾等重要脏器的基本状况，发现常见疾病的相关征兆，或初步排除常见疾病。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 10793,
		"modifiedon": "2009-04-13 11:17:44",
		"ipaddress": "219.142.28.50",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "内科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"皮肤",
			"浅表淋巴结",
			"甲状腺(外科)",
			"乳房",
			"脊柱",
			"四肢关节",
			"外生殖器",
			"肛门、直肠指诊",
			"外科其它"
		],
		"id": 2,
		"code": "1.5.1.1",
		"py": "NWK",
		"name": "外科",
		"showindex": 10,
		"sexid": 1,
		"depttypeid": 17,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过体格检查，检查性皮肤、甲状腺、脊柱四肢、外生殖器等重要脏器基本情况，发现常见外科疾病的相关征兆，或初步排除外科常见疾病。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 35601,
		"modifiedon": "2017-07-21 10:51:23",
		"ipaddress": "192.168.2.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "外科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"裸视力(右)",
			"裸视力(左)",
			"矫正视力(右)",
			"矫正视力(左)",
			"色觉"
		],
		"id": 3,
		"code": "1.1.1.15",
		"py": "SL SJ",
		"name": "视力 色觉",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 1,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "了解视力状况，判断眼睛视力、色觉功能。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2023-11-27 15:00:49",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "眼科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"裂隙灯检查"
		],
		"id": 4,
		"code": "1.1.1.8",
		"py": "LXDJC",
		"name": "裂隙灯检查",
		"showindex": 12,
		"sexid": 2,
		"depttypeid": 1,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过裂隙灯检查巩膜、虹膜、角膜、瞳孔、玻璃体等有无异常情况。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2023-11-27 15:04:05",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "眼科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"眼底镜检查"
		],
		"id": 5,
		"code": "1.1.1.5",
		"py": "YKE",
		"name": "眼底镜检查",
		"showindex": 13,
		"sexid": 2,
		"depttypeid": 1,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过眼底镜检查眼底视网膜、视神经乳头和视网膜中央血管等有无异常情况。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2023-11-27 15:06:03",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "眼科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"右眼非接触性眼压",
			"左眼非接触性眼压"
		],
		"id": 6,
		"code": "1.1.1.6",
		"py": "FJCXYYCL",
		"name": "非接触性眼压测量",
		"showindex": 14,
		"sexid": 2,
		"depttypeid": 1,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "眼压的检查是发现青光眼的三大重要检查之一，也是最简单的检查。以排除高眼压和青光眼的可能性，可早期发现病变并进行治疗，也可用于病程的疗效评价。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2023-11-27 15:07:28",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "眼科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"既往史",
			"外耳",
			"外耳道",
			"鼓膜",
			"鼻腔",
			"鼻中隔",
			"咽",
			"扁桃体",
			"耳鼻咽喉科其它"
		],
		"id": 7,
		"code": "1.6.1.3",
		"py": "EBYHK",
		"name": "耳鼻咽喉科",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 19,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过对耳、鼻、咽、扁桃喉等器官的常规检查，初步筛查常见疾病。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 10793,
		"modifiedon": "2009-08-22 11:32:29",
		"ipaddress": "59.42.106.218",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "耳鼻咽喉科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"唇",
			"牙体",
			"牙周",
			"舌",
			"腭",
			"口腔粘膜",
			"颞下颌关节",
			"口腔科其它",
			"口腔腺体",
			"牙列"
		],
		"id": 8,
		"code": "1.7.1.1",
		"py": "KQK",
		"name": "口腔科",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 21,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "口腔常规检查，全面了解口腔健康状况，及时发现口腔科常见疾病。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "科室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2024-03-01 14:01:37",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 1,
		"depttypename": "口腔科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"白细胞计数",
			"红细胞计数",
			"血红蛋白",
			"红细胞压积",
			"平均红细胞体积",
			"平均红细胞血红蛋白含量",
			"平均红细胞血红蛋白浓度",
			"红细胞分布宽度-变异系数",
			"血小板计数",
			"平均血小板体积",
			"血小板分布宽度",
			"淋巴细胞百分比",
			"中间细胞百分比",
			"中性粒细胞百分比",
			"淋巴细胞绝对值",
			"中间细胞绝对值",
			"中性粒细胞绝对值",
			"红细胞分布宽度-标准差",
			"血小板压积"
		],
		"id": 9,
		"code": "2.1.1.113",
		"py": "XCG",
		"name": "血常规",
		"showindex": 12,
		"sexid": 2,
		"depttypeid": 3,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过检测血液细胞的计数及不同种类细胞、成分的分类来反映身体状况，如：贫血、感染等等。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "实验室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2024-03-29 17:07:41",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 2,
		"depttypename": "检验科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"尿比重",
			"尿酸碱度",
			"尿白细胞",
			"尿亚硝酸盐",
			"尿蛋白质",
			"尿糖",
			"尿酮体",
			"尿胆原",
			"尿胆红素",
			"尿隐血",
			"尿镜检红细胞",
			"尿镜检白细胞",
			"管型",
			"上皮细胞",
			"无机盐类"
		],
		"id": 10,
		"code": "2.1.1.114",
		"py": "NCG",
		"name": "尿常规",
		"showindex": 22,
		"sexid": 2,
		"depttypeid": 3,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "用于检查泌尿系统疾病，如泌尿系统感染、肿瘤、结石及了解肾功能，还可用于协助检查其他系统疾病，如糖尿病、高血压、肝炎等。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "实验室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2023-12-13 11:40:55",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 2,
		"depttypename": "检验科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"丙氨酸氨基转移酶",
			"天门冬氨酸氨基转移酶"
		],
		"id": 11,
		"code": "2.1.1.12",
		"py": "GGEX",
		"name": "肝功二项",
		"showindex": 39,
		"sexid": 2,
		"depttypeid": 3,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "可较好地了解肝脏功能状况。ALT、 AST主要存在于肝心脑肾组织细胞内，肝细胞损伤越大ALT、 AST就越高。急慢性肝炎、脂肪肝、肝硬化、肝癌等疾病均可引起ALT、 AST升高。",
		"promptinfo": "空腹采血",
		"normalinfo": "",
		"checktypename": "实验室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 10793,
		"modifiedon": "2009-06-05 08:38:01",
		"ipaddress": "219.142.28.50",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 2,
		"depttypename": "检验科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"肌酐"
		],
		"id": 12,
		"code": "2.1.1.22",
		"py": "SGYX",
		"name": "肾功一项",
		"showindex": 390,
		"sexid": 2,
		"depttypeid": 3,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "用于肾功能评价，测定肾功能损害程度及估计预后。",
		"promptinfo": "空腹采血",
		"normalinfo": "",
		"checktypename": "实验室检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 10793,
		"modifiedon": "2009-03-23 10:53:12",
		"ipaddress": "219.142.28.50",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 2,
		"depttypename": "检验科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"肝",
			"胆",
			"胰",
			"脾",
			"双肾"
		],
		"id": 13,
		"code": "3.2.1.1",
		"py": "FBCC",
		"name": "腹部彩超",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 4,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "对人体腹部内脏器官（肝、胆、脾、胰、双肾）的状况和各种病变（如肿瘤、结石、积水、脂肪肝等）提供高清晰度的彩色动态超声断层图像判断，依病灶周围血管情况、病灶内血流血供情况-良恶性病变鉴别；判断肾动脉狭窄等。",
		"promptinfo": "空腹检查",
		"normalinfo": "",
		"checktypename": "医技检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 10793,
		"modifiedon": "2011-05-23 08:12:47",
		"ipaddress": "219.142.28.50",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 3,
		"depttypename": "超声检查室",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"胸部"
		],
		"id": 14,
		"code": "3.1.1.41",
		"py": "XBZW(IKANGAI )",
		"name": "胸部正位(iKangAI+)",
		"showindex": 12,
		"sexid": 2,
		"depttypeid": 2,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过X线拍片检查两肺、心脏、纵隔、膈、胸膜，判断有无炎症、肿瘤等。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "医技检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2024-03-12 16:11:36",
		"ipaddress": "10.33.21.88",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 3,
		"depttypename": "放射科",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	},
	{
		"indexs": [
			"心电图"
		],
		"id": 15,
		"code": "3.3.1.1",
		"py": "XDT(IKANGAI )",
		"name": "心电图(iKangAI+)",
		"showindex": 10,
		"sexid": 2,
		"depttypeid": 13,
		"itemsortbyassayid": 0,
		"sampletypeid": 0,
		"ispreprandial": 0,
		"clinicmeaning": "通过在体表特定部位同步记录和分析心脏每一个心动周期所产生电活动变化的曲线图形，为心脏疾病诊断、疗效评价、预后评估提供重要的依据。",
		"promptinfo": "",
		"normalinfo": "",
		"checktypename": "医技检查",
		"category": 0,
		"isfront": 0,
		"operatormemo": "",
		"status": 1,
		"operatorid": 16901,
		"modifiedon": "2024-03-18 14:00:18",
		"ipaddress": "10.33.21.87",
		"limittype": 0,
		"salesPrice": 0,
		"additemAllowance": 0,
		"checktypeid": 3,
		"depttypename": "心电图室",
		"packageprompt": "",
		"baseprice": 0,
		"isikang": 0,
		"hasKnowledge": 0
	}
]

fs.writeFileSync('./check.js', JSON.stringify(ksChecks.map(item => {
  return {
    name: item.name,
    id: item.id
  }
})))